### ISSUE TITLE
Data set trained on?

### ISSUE THREAD

**Issue by sidhomj** [WesleyyC/Amino-Acid-Embedding#1]
Can you specify which data-set you trained on to bring you to that t-SNE plot?

Thanks..

**Comment by WesleyyC** [comment]
Hi,

The data is from RefSeq:
https://www.biostars.org/p/130274/

And you can pull them down with this python helper:
https://github.com/WesleyyC/Amino-Acid-Embedding/blob/master/Data/getFileWeb.py

Cheers

**Comment by zyxue** [comment]
How many peptides were used exactly, please?
